# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Ham-Reference-QRZ
version:      0.02
version_from: lib/Ham/Reference/QRZ.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Test::More:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
